---

version: '3.5'

services:

  hasura:
    image: 'hasura/graphql-engine:v1.3.0'
    hostname: 'hasura-dev'
    container_name: 'hasura-dev-container'
    depends_on:
      - 'hasura-db'
    tmpfs: '/tmp'
    ports:
      - target: '8082'
        published: '8082'
    restart: 'always'
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@hasura-db:5432/${POSTGRES_DB:-postgres}
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=true

  hasura-db:
    image: 'postgres:alpine'
    hostname: 'hasura-db'
    container_name: 'hasura-db-container'
    tmpfs: '/tmp'
    volumes:
      - type: volume
        source: hasura-db-data
        target: /var/lib/postgresql/data
    restart: 'always'
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  postgrest:
    image: 'postgrest/postgrest'
    hostname: 'postgrest-dev'
    container_name: 'postgrest-dev-container'
    depends_on:
      - 'hasura-db'
    tmpfs: '/tmp'
    ports:
      - target: '3000'
        published: '8081'
    restart: 'always'
    environment:
      - PGRST_DB_URI=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@hasura-db:5432/${POSTGRES_DB:-postgres}
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=postgres

volumes:
  hasura-db-data:
